### ISSUE TITLE
Allow users to select different teams from all regions and seasons.

### ISSUE THREAD

**Issue by lukezhang454** [lukezhang454/Pro2Pro#3]
Implement a new dropdown menu for the playing season and another menu for all of the different regions in the world. Currently the teams list and stats are only populated by the 2017 NA LCS summer season statistics.

**Comment by lukezhang454** [comment]
Currently required api's to populate dropdowns and stat tables are:

- `/api/seasons` returns all selectable seasons
- `/api/seasons/{season}/regions` returns all selectable regions
- `/api/seasons/{season}/regions/{region}/teams` returns all of the teams in a region
- `/api/seasons/{season}/regions/{region}/teams/{team}` return all players on the team and their statistics

**Comment by RyanYip** [comment]
The current endpoints have been implemented. Additional endpoints may added later as needed. Closing for completion.
